# -*- coding: utf-8 -*-
"""Assignment5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12vnRlQ1JjLaNiqy3LyBEHyplCFQbxUis
"""

!pip install kgtk==1.0.1

!echo "deb http://downloads.skewed.de/apt bionic main" >> /etc/apt/sources.list
!apt-key adv --keyserver keys.openpgp.org --recv-key 612DEFB798507F25
!apt-get update
!apt-get install python3-graph-tool python3-cairo python3-matplotlib
!apt-get install libcairo2-dev

"""## Preamble: set up the environment and files used in the assignment (remember to restart runtime)"""

import io
import os
import subprocess
import sys

import math
import numpy as np
import pandas as pd
from graph_tool.all import *
from IPython.display import display, HTML

from kgtk.configure_kgtk_notebooks import ConfigureKGTK
from kgtk.functions import kgtk, kypher

# Parameters

# Folder on local machine where to create the output and temporary folders
input_path = None
output_path = "/tmp/projects"
project_name = "assignment"

"""The following command will download all the files you  need for the assignment:"""

files = [
    "all",
    "label",
    "alias",
    "description",
    "external_id",
    "monolingualtext",
    "quantity",
    "string",
    "time",
    "item",
    "wikibase_property",
    "qualifiers",
    "datatypes",
    "p279",
    "p279star",
    "p31",
    "in_degree",
    "out_degree",
    "pagerank_directed",
    "pagerank_undirected"
]
ck = ConfigureKGTK(files)
ck.configure_kgtk(input_graph_path=input_path,
                  output_path=output_path,
                  project_name=project_name)

"""The KGTK setup command defines environment variables for all the files so that you can reuse the Jupyter notebook when you install it on your local machine."""

ck.print_env_variables()

# Commented out IPython magic to ensure Python compatibility.
# %%time
# ck.load_files_into_cache()

"""# About this assignment.
This assignment is based on https://github.com/usc-isi-i2/kgtk-notebooks/tree/main/tutorial. If you have any questions or doubts, it is encouraged to look how the tutorial performs the different operations.

Additional information can be found in https://kgtk.readthedocs.io/

## Simple graph statistics

Let's calculate first some statistics about the KG. Count the number of instances:
"""

# Commented out IPython magic to ensure Python compatibility.
# %%time
# kgtk("""
#      query -i all \
#      --match '(inst)-[:P31]->(v)' \
#      --return 'count(inst) as INUM'
# """)

"""Now, count the number of distinct properties: 

"""

# Commented out IPython magic to ensure Python compatibility.
# %%time
# kgtk("""
#      query -i all \
#      --match '(instance)-[l {label: property}]->(class)' \
#      --return 'count(distinct property) as NUMPROP'
# """)

"""Now, let's count the frequency of those properties. That is, how many instances we can find with each property"""

# Commented out IPython magic to ensure Python compatibility.
# %%time
# kgtk("""
#     query -i all \
#      --match '(instance)-[l {label: property}]->(class)' \
#      --return 'distinct property as PROP, count(instance) as FREQ' \
#      --order-by 'count(instance) desc' 
# """)

"""## Simple queries
Installation and preparation of environment to run SPARQL queries to Wikidata
"""

# Instalar paquete
!pip install sparqlwrapper
# Importar paquetes y preparar entorno (SPARQL)
from SPARQLWrapper import SPARQLWrapper, JSON
import pandas as pd
sparql = SPARQLWrapper("https://query.wikidata.org/sparql")

"""Some of these queries are simple and will run in the Wikidata endpoint. Try both of them using SPARQL and Kypher"""

# Which actors has Schwarzenegger worked with throughout his career? (Print also the movie)
# (in SPARQL)
sparql.setQuery('''
  SELECT ?actor_label ?actor_id ?movie_label ?movie_id 
  WHERE {
      ?movie_id wdt:P161 wd:Q2685 . # Q2685 (Arnold Schwarzenegger)
      ?movie_id wdt:P161 ?actor_id .
      ?actor_id rdfs:label ?actor_label .
      ?movie_id rdfs:label ?movie_label .
      FILTER(?actor_id != wd:Q2685) .
      FILTER(LANG(?actor_label) = 'en')
      FILTER(LANG(?movie_label) = 'en')
  }
  ORDER BY ?actor_label
''')
sparql.setReturnFormat(JSON)
results = sparql.query().convert()

# Result (SPARQL)
results_df = pd.io.json.json_normalize(results['results']['bindings'])
results_df[['actor_label.value', 'movie_label.value']].head()

# In Kypher:
kgtk("""
    query -i all \
     --match '(movies)-[:P161]->(:Q2685),
              (movies)-[:P161]->(actors)' \
     --return 'actors' 
    / add-labels
""")

# How many awards does Schwarzenegger have?

# SPARQL:
sparql.setQuery('''
  SELECT ?award_label ?award
  WHERE {
      wd:Q2685 wdt:P166 ?award . # Q2685 (Arnold Schwarzenegger)
      ?award rdfs:label ?award_label .
      FILTER(LANG(?award_label) = 'en')
  }
  ORDER BY ?award_label
''')
sparql.setReturnFormat(JSON)
results = sparql.query().convert()

# Result (SPARQL)
results_df = pd.io.json.json_normalize(results['results']['bindings'])
results_df[['award_label.value', 'award.value']].head()

# In Kypher:
kgtk("""
    query -i all \
     --match '(:Q2685)-[:P166]->(awards)' \
     --return 'awards' 
    / add-labels
""")

# Retrieve at least two members of Schwarzenegger's political party. Make sure only persons are returned
# SPARQL:
sparql.setQuery('''
  SELECT ?member_label ?member_id ?political_label ?political_id 
  WHERE {
      wd:Q2685 wdt:P102 ?political_id .
      ?member_id wdt:P102 ?political_id .
      ?member_id wdt:P31 wd:Q5 .
      ?member_id rdfs:label ?member_label .
      ?political_id rdfs:label ?political_label .
      FILTER(LANG(?member_label) = 'en') .
      FILTER(LANG(?political_label) = 'en')
  }
  ORDER BY ?member_label
  LIMIT 5
''')
sparql.setReturnFormat(JSON)
results = sparql.query().convert()

# Result (SPARQL)
results_df = pd.io.json.json_normalize(results['results']['bindings'])
results_df[['member_label.value', 'political_label.value']].head()

# In Kypher:
kgtk("""
    query -i all \
     --match '(:Q2685)-[:P102]->(parties),
              (members)-[:P102]->(parties),
              (members)-[:P31]->(:Q5)' \
     --return 'members' 
    / add-labels
""")

# What are the properties that describe an artist?

# In theory this one is heavy on Wikidata

# SPARQL:
sparql.setQuery('''
  SELECT DISTINCT ?prop ?val
  WHERE {
      wd:Q483501 ?prop ?val .
      ?wdprop wikibase:directClaim ?prop .
      ?wdprop wdt:P31+ wd:Q107649491
  }
''')
sparql.setReturnFormat(JSON)
results = sparql.query().convert()

# Result (SPARQL)
results_df = pd.io.json.json_normalize(results['results']['bindings'])
results_df[['prop.value', 'val.value']].head()

# In Kypher:
kgtk("""
    query -i all \
     --match '(class)-[:P279*]->(:Q483501),
              (class)-[l {label: property}]->(value)' \
     --return 'distinct property' 
    / add-labels
""")

# And a film director?
# SPARQL:
sparql.setQuery('''
  SELECT DISTINCT ?prop ?val
  WHERE {
      wd:Q2526255 ?prop ?val .
      ?wdprop wikibase:directClaim ?prop .
      ?wdprop wdt:P31+ wd:Q107649491
  }
''')
sparql.setReturnFormat(JSON)
results = sparql.query().convert()

# Result (SPARQL)
results_df = pd.io.json.json_normalize(results['results']['bindings'])
results_df[['prop.value', 'val.value']].head()

# In Kypher:
kgtk("""
    query -i all \
     --match '(class)-[:P279*]->(:Q2526255),
              (class)-[l {label: property}]->(value)' \
     --return 'distinct property' 
    / add-labels
""")

# Embeddings. Run the noebook https://colab.research.google.com/drive/1A55l10voA4jnjoju3fojJWY3buLfaR4i?usp=sharing. 
# Which are the top 10 similar entities to Schwarzenegger? (list below) 
print("Nearest points in the original space (Cosine):")
print("   (1) Samuel L. Jackson [0.099]")
print("   (2) Carl Reiner [0.102]")
print("   (3) Neville Brand [0.110]")
print("   (4) Jess Hill [0.113]")
print("   (5) Leonard Nimoy [0.114]")
print("   (6) Steven Ford [0.123]")
print("   (7) Ross Hill [0.129]")
print("   (8) Joe Morton [0.129]")
print("   (9) Mako [0.131]")
print("   (10) Telly Savalas [0.132]")

"""## Network analysis
Print all the paths between Schwarzenegger and Trump

## Note that **you have to create a file `paths.tsv` with the node pairs you want to find the paths for. Upload it in the "content" folder**

"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cat <<EOF >$TEMP/path-query.tsv
# node1	node2	label
# Q2685	Q22686	path

kgtk("""
    add-labels -i $TEMP/path-query.tsv
""")

# Calculate all the paths between Trump and Schwarzenegger (max hops: 3)
kgtk("""
    paths -i all
    --max_hops 3 
    --shortest-path False
    --statistics-only True
    --path-file $TEMP/path-query.tsv
    -o /content/01-path_results.tsv
""")

# Retrieve all the family of Schwarzenegger (child/father/mother/sibling/spouse relationships)
kgtk("""
    reachable-nodes -i $item
        --root Q2685
        --props P40 P3373 P26 P451 P22 P25
        --label Pextended_family
    -o /content/02-path_results.tsv
    / add-labels
""")

# What are the 10 most relevant actors (pagerank) in the graph? (Use graph-statistics command to calculate page rank, and then filter only actors)
kgtk("""
  graph-statistics -i "$item" -o $OUT/metadata.pagerank.undirected.tsv.gz 
    --compute-pagerank True 
    --compute-hits False 
    --page-rank-property Pdirected_pagerank 
    --vertex-in-degree-property Pindegree
    --vertex-out-degree-property Poutdegree
    --output-degrees True 
    --output-pagerank True 
    --output-hits False \
    --output-statistics-only 
    --undirected True 
    --log-file $TEMP/metadata.pagerank.undirected.summary.txt
""")

# TO DO: Hint: do the query after calculating the pagerank. See https://github.com/usc-isi-i2/kgtk-notebooks/blob/main/tutorial/06-kg-network-analysis.ipynb for inspiration
kgtk("""
    query -i item -i $OUT/metadata.pagerank.undirected.tsv.gz
        --match '
            item: (actor)-[:P106]->(:Q33999),
            pagerank: (actor)-[:Pdirected_pagerank]->(pagerank)'
        --return 'actor as node1, pagerank as node2'
        --order-by 'cast(pagerank, float) desc'
        --limit 10
    / add-labels
""")