# -*- coding: utf-8 -*-
"""Task09 - Data Linking.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zD67R0nKL24JIiIJPSkqpKEu0oRlLCfK

**Task 09: Data linking**
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials/"

from rdflib import Graph, Namespace, Literal, URIRef
g1 = Graph()
g2 = Graph()
g3 = Graph()
g1.parse(github_storage+"rdf/data03.rdf", format="xml")
g2.parse(github_storage+"rdf/data04.rdf", format="xml")

"""Busca individuos en los dos grafos y enlázalos mediante la propiedad OWL:sameAs, inserta estas coincidencias en g3. Consideramos dos individuos iguales si tienen el mismo apodo y nombre de familia. Ten en cuenta que las URI no tienen por qué ser iguales para un mismo individuo en los dos grafos."""

# Consideramos dos individuos iguales si tienen el mismo apodo y nombre de familia
from rdflib import URIRef

given = URIRef("http://www.w3.org/2001/vcard-rdf/3.0#Given")
family = URIRef("http://www.w3.org/2001/vcard-rdf/3.0#Family")
data = URIRef("http://data.three.org#")
owl = Namespace("http://www.w3.org/2002/07/owl#")

inds_g1 = list()
inds_g2 = list()
for s1, p1, o1 in g1.triples((None, given, None)):
  for s2, p2, o2 in g2.triples((None, given, None)):
    # If the given names are the same, save the entity's URI in two lists.
    if str(o1) == str(o2):
      inds_g1.append(s1)
      inds_g2.append(s2)

for i in range(len(inds_g1)):
  # print(g1.value(inds_g1[i], family, None))
  # print(g2.value(inds_g2[i], family, None))
  # print(str(g1.value(inds_g1[i], family, None)) == str(g2.value(inds_g2[i], family, None)))
  if str(g1.value(inds_g1[i], family, None)) == str(g2.value(inds_g2[i], family, None)):
    g3.add((inds_g1[i], owl.sameAs, inds_g2[i]))