# -*- coding: utf-8 -*-
"""Assignment-Notebook-David-Lorenzo-Alfaro.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16c6pAeBkYU15qEDMEdlEWEY7lXcITZ_q
"""

# !pip install kgtk==1.0.1

# !echo "deb http://downloads.skewed.de/apt bionic main" >> /etc/apt/sources.list
# !apt-key adv --keyserver keys.openpgp.org --recv-key 612DEFB798507F25
# !apt-get update
# !apt-get install python3-graph-tool python3-cairo python3-matplotlib
# !apt-get install libcairo2-dev

"""## Preamble: set up the environment and files used in the assignment (remember to restart runtime)"""

import io
import os
import subprocess
import sys

import math
import numpy as np
import pandas as pd
from graph_tool.all import *
from IPython.display import display, HTML

from kgtk.configure_kgtk_notebooks import ConfigureKGTK
from kgtk.functions import kgtk, kypher

# Parameters

# Folder on local machine where to create the output and temporary folders
input_path = None
output_path = "/tmp/projects"
project_name = "assignment"

"""The following command will download all the files you  need for the assignment:"""

files = [
    "all",
    "label",
    "alias",
    "description",
    "external_id",
    "monolingualtext",
    "quantity",
    "string",
    "time",
    "item",
    "wikibase_property",
    "qualifiers",
    "datatypes",
    "p279",
    "p279star",
    "p31",
    "in_degree",
    "out_degree",
    "pagerank_directed",
    "pagerank_undirected"
]
ck = ConfigureKGTK(files)
ck.configure_kgtk(input_graph_path=input_path,
                  output_path=output_path,
                  project_name=project_name)

"""The KGTK setup command defines environment variables for all the files so that you can reuse the Jupyter notebook when you install it on your local machine."""

ck.print_env_variables()

# %%time
ck.load_files_into_cache()

"""# About this assignment.
This assignment is based on https://github.com/usc-isi-i2/kgtk-notebooks/tree/main/tutorial. If you have any questions or doubts, it is encouraged to look how the tutorial performs the different operations.

Additional information can be found in https://kgtk.readthedocs.io/

## Simple graph statistics

Let's calculate first some statistics about the KG. Count the number of instances:
"""

# %%time
kgtk("""
    query -i all
        --match '(instance)-[:P31]->()'
        --return 'count(distinct instance) as count_instances'
""")

"""Now, count the number of distinct properties: 

"""

# %%time
kgtk("""
    query -i all
        --match '()-[p]->()'
        --return 'count(distinct p.label) as count_properties'
""")

# Alternatively, we can do the query as follows:
# kgtk("""
#     query -i all
#         --match '()-[l {label: property}]->()'
#         --return 'count(distinct property) as count_property'
# """)

"""Now, let's count the frequency of those properties. That is, how many instances we can find with each property"""

# %%time
kgtk("""
    query -i all
        --match '(i)-[p]->()'
        --return 'p.label, count(distinct i) as count_properties'
        --order-by 'cast(count_properties,int) desc'
        / add-labels
""")

"""## Simple queries
Some of these queries are simple and will run in the Wikidata endpoint. 
Try both of them using SPARQL and Kypher
"""

# Which actors has Schwarzenegger worked with throughout his career? (Print also the movie)

# (in SPARQL)
query = """SELECT ?colleage ?colleageLabel ?film ?filmLabel
WHERE
{
  ?film wdt:P161 wd:Q2685.
  ?film wdt:P161 ?colleage.
  FILTER(?colleage != wd:Q2685)
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
}"""

# In Kypher:
kgtk("""
  query -i all
    --match '(colleage)<-[:P161]-(film)-[:P161]->(:Q2685)'
    --where 'colleage != "Q2685"'
    --return 'colleage, film'
    / add-labels
""")

# How many awards does Schwarzenegger have?

# SPARQL:
query= """SELECT (COUNT(?award) AS ?num_awards)
WHERE 
{
  wd:Q2685 wdt:P166 ?award
}"""

# Kypher:
kgtk("""
    query -i all
        --match '(:Q2685)-[:P166]->(award)'
        --return 'count(award) as num_awards'
""")

# Retrieve at least two members of Schwarzenegger's political party. Make sure only persons are returned
# SPARQL:
query = """SELECT ?member ?political_party
WHERE
{
  wd:Q2685 wdt:P102 ?political_party.
  ?member wdt:P102 ?political_party.
  ?member wdt:P31 wd:Q5.
  FILTER (?member != wd:Q2685)
}
"""

# Kypher:
kgtk("""
    query -i all
        --match '(:Q2685)-[:P102]->(political_party)<-[:P102]-(member)-[:P31]->(:Q5)'
        --where 'member != "Q2685"'
        --return 'member, political_party'
    / add-labels
""")

# What are the properties that describe an artist?

# In theory this one is heavy on Wikidata

# SPARQL: 
query = """SELECT DISTINCT ?property
WHERE
{
  ?class rdfs:subClassOf* wd:Q483501.
  ?subject wdt:P106 ?class.
  ?subject ?property ?p.
}
"""


# In Kypher:
kgtk("""
    query -i all
        --match '()<-[l {label: property}]-()-[:P279*]->(:Q483501)'
        --return 'distinct property'
""")

# And a film director?
# SPARQL:
query = """SELECT DISTINCT ?property 
WHERE {
        ?class rdfs:subClassOf* wd:Q2526255.
        ?subject wdt:P106* ?class.
        ?subject ?property ?p.
}
"""

# In Kypher:
kgtk("""
    query -i all
        --match '()<-[l {label: property}]-()-[:P279*]->(:Q2526255)'
        --return 'distinct property'
""")

# Embeddings. Run the noebook https://colab.research.google.com/drive/1A55l10voA4jnjoju3fojJWY3buLfaR4i?usp=sharing. 
# Which are the top 10 similar entities to Schwarzenegger? (list below) 
""" 
  * Arnold Schwarzenegger
  * Hugh O'Brian
  * John Larroquette
  * Carl Reiner
  * Harvey Fierstein
  * Tom Sizemore
  * Randy Quaid
  * Gene Kelly
  * DeForest Kelley
  * Robert Stack
'''

"""## Network analysis
Print all the paths between Schwarzenegger and Trump

## Note that **you have to create a file `paths.tsv` with the node pairs you want to find the paths for. Upload it in the "content" folder**

"""

# %%bash
# cat <<EOF >$TEMP/path-query.tsv
# node1	node2	label
# Q2685	Q22686	path

kgtk("""
    add-labels -i $TEMP/path-query.tsv
""")

# Calculate all the paths between Trump and Schwarzenegger (max hops: 3)
# TO DO    
kgtk("""
  paths -i all
          --path-file /tmp/projects/assignment/temp.assignment/path-query.tsv
          --statistics-only True
          --max_hops 3
""")

# Retrieve all the family of Schwarzenegger (child/father/mother/sibling/spouse relationships)
# TO DO  
kgtk("""
    reachable-nodes -i all
        --root Q2685
        --props P40 P3373 P26 P451 P22 P25
        --label hasFamiliar
    / add-labels
""")

# What are the 10 most relevant actors (pagerank) in the graph? (Use graph-statistics command to calculate page rank, and then filter only actors)
# TO DO  
kgtk("""
    graph-statistics -i all -o /tmp/projects/assignment/metadata.pagerank.undirected.tsv.gz
    --compute-pagerank True
    --compute-hits False
    --page-rank-property P_pagerank
    --output-pagerank True
    --output-statistics-only
    --output-hits False
    --undirected True
    --log-file /tmp/projects/assignment/metadata.pagerank.undirected.summary.txt
""")

# TO DO: Hint: do the query after calculating the pagerank. See https://github.com/usc-isi-i2/kgtk-notebooks/blob/main/tutorial/06-kg-network-analysis.ipynb for inspiration
kgtk("""
    query  -i all -i /tmp/projects/assignment/metadata.pagerank.undirected.tsv.gz
        --match '
            all: (actor)-[:P106]->(:Q33999),
            pagerank: (actor)-[:P_pagerank]->(pagerank)'
        --return 'actor as node1, pagerank as node2'
        --order-by 'cast(pagerank, float) desc'
        --limit 10
    / add-labels
""")