# -*- coding: utf-8 -*-
"""Copia de Assignment-Notebook.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PeR71qmRCGhOIYUb1xRZb4USOXoo8Vqc
"""

# !pip install kgtk==1.0.1
#
# !echo "deb http://downloads.skewed.de/apt bionic main" >> /etc/apt/sources.list
# !apt-key adv --keyserver keys.openpgp.org --recv-key 612DEFB798507F25
# !apt-get update
# !apt-get install python3-graph-tool python3-cairo python3-matplotlib
# !apt-get install libcairo2-dev
# !pip install pycairo

"""## Preamble: set up the environment and files used in the assignment (remember to restart runtime)"""

import io
import os
import subprocess
import sys

import math
import numpy as np
import pandas as pd
from graph_tool.all import *
from IPython.display import display, HTML

from kgtk.configure_kgtk_notebooks import ConfigureKGTK
from kgtk.functions import kgtk, kypher

import graph_tool.all as gt

# Parameters

# Folder on local machine where to create the output and temporary folders
input_path = None
output_path = "/tmp/projects"
project_name = "assignment"

"""The following command will download all the files you  need for the assignment:"""

files = [
    "all",
    "label",
    "alias",
    "description",
    "external_id",
    "monolingualtext",
    "quantity",
    "string",
    "time",
    "item",
    "wikibase_property",
    "qualifiers",
    "datatypes",
    "p279",
    "p279star",
    "p31",
    "in_degree",
    "out_degree",
    "pagerank_directed",
    "pagerank_undirected"
]
ck = ConfigureKGTK(files)
ck.configure_kgtk(input_graph_path=input_path,
                  output_path=output_path,
                  project_name=project_name)

"""The KGTK setup command defines environment variables for all the files so that you can reuse the Jupyter notebook when you install it on your local machine."""

ck.print_env_variables()

# Commented out IPython magic to ensure Python compatibility.
# %%time
# ck.load_files_into_cache()

# SPARQL Stuff
# ! pip install sparqlwrapper
# https://rdflib.github.io/sparqlwrapper/

import sys
from SPARQLWrapper import SPARQLWrapper, JSON

endpoint_url = "https://query.wikidata.org/sparql"


def get_results(endpoint_url, query):
    user_agent = "WDQS-example Python/%s.%s" % (sys.version_info[0], sys.version_info[1])
    # TODO adjust user agent; see https://w.wiki/CX6
    sparql = SPARQLWrapper(endpoint_url, agent=user_agent)
    sparql.setQuery(query)
    sparql.setReturnFormat(JSON)
    return sparql.query().convert()

"""# About this assignment.
This assignment is based on https://github.com/usc-isi-i2/kgtk-notebooks/tree/main/tutorial. If you have any questions or doubts, it is encouraged to look how the tutorial performs the different operations.

Additional information can be found in https://kgtk.readthedocs.io/

## Simple graph statistics

Let's calculate first some statistics about the KG. Count the number of instances:
"""

# Commented out IPython magic to ensure Python compatibility.
# %%time
# kgtk("""
#     query -i all
#     --match '(r)-[]->()' \
#     --return 'count(r) as N'
# """)

"""Now, count the number of distinct properties:

"""

# Commented out IPython magic to ensure Python compatibility.
# %%time
# kgtk("""
#     query -i all
#     --match '()-[r]->()' \
#     --return 'count(distinct r.label) as N'
# """)

"""Now, let's count the frequency of those properties. That is, how many instances we can find with each property"""

# Commented out IPython magic to ensure Python compatibility.
# %%time
# kgtk("""
#     query -i all
#     --match '()-[r]->()' \
#     --return 'distinct r.label, count(r) as Number'
# """)

"""## Simple queries
Some of these queries are simple and will run in the Wikidata endpoint.
Try both of them using SPARQL and Kypher
"""

# Which actors has Schwarzenegger worked with throughout his career? (Print also the movie)

# (in SPARQL)
query = """select * where{
  ?film wdt:P161 wd:Q2685.
  ?film wdt:P161 ?actor.
  FILTER(?film != wd:Q2685)
}"""
results = get_results(endpoint_url, query)

for result in results["results"]["bindings"]:
    print('Movie: ',result['film']['value'])
    print('Actor: ',result['actor']['value'])
    print('')

# In Kypher:
kgtk("""
    query -i all
    --match '(:Q2685)<-[:P161]-(film)-[:P161]->(actor)' \
    --where 'actor != "Q2685"' \
    --return 'film as Film, actor as Actor' \
    / add-labels
""")

# How many awards does Schwarzenegger have?

# SPARQL:
query = """select (count(?award) as ?count) where{
  wd:Q2685 wdt:P166 ?award
}"""

results = get_results(endpoint_url, query)

for result in results["results"]["bindings"]:
    print('Award counter: ',result['count']['value'])

# Kypher:
kgtk("""
    query -i all
    --match '(:Q2685)-[:P166]->(award)' \
    --return 'count(distinct award) as Num_Awards'
""")

# Retrieve at least two members of Schwarzenegger's political party. Make sure only persons are returned
# SPARQL:
query = """SELECT ?politician WHERE {
    wd:Q2685 wdt:P102 ?party.
    ?politician wdt:P102 ?party
    }"""

results = get_results(endpoint_url, query)

for result in results["results"]["bindings"]:
    print(result['politician']['value'])

# Kypher:
kgtk("""
    query -i all
    --match '(:Q2685)-[:P102]->(party)<-[:P102]-(politician)-[:P31]->(Q5)' \
    --return 'distinct politician as Politician' \
    / add-labels
""")

# What are the properties that describe an artist?

# In theory this one is heavy on Wikidata

# SPARQL:
query = """SELECT distinct ?prop WHERE {
  ?artist wdt:P106 ?proffesion.
  ?proffesion wdt:P279* wd:Q483501.
  ?artist ?prop ?x
} LIMIT 20""" # Límite necesario para que se ejecute en tiempo razonable

results = get_results(endpoint_url, query)

for result in results["results"]["bindings"]:
    print(result['prop']['value'])


# In Kypher:
kgtk("""
    query -i all
    --match '()<-[l {label: property}]-()-[:P106]->()-[:P279*]->(:Q483501)' \
    --return 'distinct property as Property'
""")

# And a film director?
# SPARQL:
query = """SELECT distinct ?prop WHERE {
  ?artist wdt:P106 wd:Q2526255.
  ?artist ?prop ?x
}LIMIT 20"""

results = get_results(endpoint_url, query)

for result in results["results"]["bindings"]:
    print(result['prop']['value'])


# In Kypher:
kgtk("""
    query -i all
    --match '()<-[l {label: property}]-()-[:P106]->(wd:Q2526255)' \
    --return 'distinct property as Property'
""")

# Embeddings. Run the noebook https://colab.research.google.com/drive/1A55l10voA4jnjoju3fojJWY3buLfaR4i?usp=sharing.
# Which are the top 10 similar entities to Schwarzenegger? (list below)
print('1. Arnold Schwarzenegger')
print('2. Terence Hill')
print('3. John McTiernan')
print('4. Jan Tříska')
print('5. David S. Goyer')
print('6. Matthew Perry')
print('7. Britney Spears')
print('8. Adolph Zukor')
print('9. Kurt Russell')
print('10. Richard Donner')

"""## Network analysis
Print all the paths between Schwarzenegger and Trump

## Note that **you have to create a file `paths.tsv` with the node pairs you want to find the paths for. Upload it in the "content" folder**

"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cat <<EOF >$TEMP/path-query.tsv
# node1	node2	label
# Q2685	Q22686	path

kgtk("""
    add-labels -i $TEMP/path-query.tsv
""")

# Calculate all the paths between Trump and Schwarzenegger (max hops: 3)
# TO DO
kgtk("""
paths -i all
        --path-file $TEMP/path-query.tsv
        --statistics-only True
        --max_hops 3
""")

# Retrieve all the family of Schwarzenegger (child/father/mother/sibling/spouse relationships)
# TO DO
kgtk("""
    reachable-nodes -i all
        --root Q2685
        --props P40 P3373 P26 P451 P22 P25
    / add-labels
""")

# What are the 10 most relevant actors (pagerank) in the graph? (Use graph-statistics command to calculate page rank, and then filter only actors)
# TO DO
kgtk("""
    graph-statistics -i "$all" -o $OUT/metadata.pagerank.undirected.tsv.gz
    --compute-pagerank True
    --compute-hits False
    --page-rank-property Pdirected_pagerank
    --vertex-in-degree-property Pindegree
    --vertex-out-degree-property Poutdegree
    --output-degrees True
    --output-pagerank True
    --output-hits False \
    --output-statistics-only
    --undirected True
    --log-file $TEMP/metadata.pagerank.undirected.summary.txt
""")

# TO DO: Hint: do the query after calculating the pagerank. See https://github.com/usc-isi-i2/kgtk-notebooks/blob/main/tutorial/06-kg-network-analysis.ipynb for inspiration
kgtk("""
    query -i item -i $OUT/metadata.pagerank.undirected.tsv.gz
        --match '
            item: (actor)-[:P106]->(:Q33999),
            pagerank: (actor)-[:Pdirected_pagerank]->(pagerank)'
        --return 'actor as node1, pagerank as node2'
        --order-by 'cast(pagerank, float) desc'
        --limit 10
    / add-labels
""")
